spring:
    application:
        name: wechat-zuul

server:
    port: 8887 #启动端口

zuul:
    host:
        max-per-route-connections: 60000
        socket-timeout-millis: 60000
        connect-timeout-millis: 60000

    routes:
          account:
                path: /account/**
          information:
                path: /information/**
          usually:
                path: /usually/**
          comment:
                path: /comment/**


ribbon:
  ReadTimeout: 60000  # 单位毫秒数
  SocketTimeout: 60000

eureka:
  client:
      serviceUrl:
                 defaultZone: http://localhost:8761/eureka/

# Swagger界面内容配置
swagger:
  title: 微信阅读app
  description: 微信接口文档
  version: 1.0.0
  termsOfServiceUrl: http://blog.exrick.cn
  contact:
    name: wechat-zuul
    url: http://blog.exrick.cn
    email: 1052461392@qq.com

logging:
  file: wechat-zuul.log
  level: com.mettre.wechat=DEBUG